//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.7

// ignore_for_file: unused_import

import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'directions_status.g.dart';

class DirectionsStatus extends EnumClass {

  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'OK')
  static const DirectionsStatus OK = _$OK;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'NOT_FOUND')
  static const DirectionsStatus NOT_FOUND = _$NOT_FOUND;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'ZERO_RESULTS')
  static const DirectionsStatus ZERO_RESULTS = _$ZERO_RESULTS;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'MAX_WAYPOINTS_EXCEEDED')
  static const DirectionsStatus MAX_WAYPOINTS_EXCEEDED = _$MAX_WAYPOINTS_EXCEEDED;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'MAX_ROUTE_LENGTH_EXCEEDED')
  static const DirectionsStatus MAX_ROUTE_LENGTH_EXCEEDED = _$MAX_ROUTE_LENGTH_EXCEEDED;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'INVALID_REQUEST')
  static const DirectionsStatus INVALID_REQUEST = _$INVALID_REQUEST;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'OVER_DAILY_LIMIT')
  static const DirectionsStatus OVER_DAILY_LIMIT = _$OVER_DAILY_LIMIT;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'OVER_QUERY_LIMIT')
  static const DirectionsStatus OVER_QUERY_LIMIT = _$OVER_QUERY_LIMIT;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'REQUEST_DENIED')
  static const DirectionsStatus REQUEST_DENIED = _$REQUEST_DENIED;
  /// The status field within the Directions response object contains the status of the request, and may contain debugging information to help you track down why the Directions service failed. The status field may contain the following values:  - `OK` indicates the response contains a valid result. - `NOT_FOUND` indicates at least one of the locations specified in the request's origin, destination, or waypoints could not be geocoded. - `ZERO_RESULTS` indicates no route could be found between the origin and destination. - `MAX_WAYPOINTS_EXCEEDED` indicates that too many waypoints were provided in the request. For applications using the Directions API as a web service, or the directions service in the Maps JavaScript API, the maximum allowed number of waypoints is 25, plus the origin and destination. - `MAX_ROUTE_LENGTH_EXCEEDED` indicates the requested route is too long and cannot be processed. This error occurs when more complex directions are returned. Try reducing the number of waypoints, turns, or instructions. - `INVALID_REQUEST` indicates that the provided request was invalid. Common causes of this status include an invalid parameter or parameter value. - `OVER_DAILY_LIMIT` indicates any of the following:     - The API key is missing or invalid.     - Billing has not been enabled on your account.     - A self-imposed usage cap has been exceeded.     - The provided method of payment is no longer valid (for example, a credit card has expired).     See the [Maps FAQ](https://developers.google.com/maps/faq#over-limit-key-error) to learn how to fix this. - `OVER_QUERY_LIMIT` indicates the service has received too many requests from your application within the allowed time period. - `REQUEST_DENIED` indicates that the service denied use of the directions service by your application. - `UNKNOWN_ERROR` indicates a directions request could not be processed due to a server error. The request may succeed if you try again. 
  @BuiltValueEnumConst(wireName: r'UNKNOWN_ERROR')
  static const DirectionsStatus UNKNOWN_ERROR = _$UNKNOWN_ERROR;

  static Serializer<DirectionsStatus> get serializer => _$directionsStatusSerializer;

  const DirectionsStatus._(String name): super(name);

  static BuiltSet<DirectionsStatus> get values => _$values;
  static DirectionsStatus valueOf(String name) => _$valueOf(name);
}

/// Optionally, enum_class can generate a mixin to go with your enum for use
/// with Angular. It exposes your enum constants as getters. So, if you mix it
/// in to your Dart component class, the values become available to the
/// corresponding Angular template.
///
/// Trigger mixin generation by writing a line like this one next to your enum.
abstract class DirectionsStatusMixin = Object with _$DirectionsStatusMixin;

